# Generated by Django 5.2.6 on 2025-09-28 16:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Faith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('size', models.CharField(choices=[('TN', 'Minúsculo'), ('SM', 'Pequeno'), ('MD', 'Médio'), ('LG', 'Grande'), ('HG', 'Enorme'), ('GG', 'Colossal')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('level', models.IntegerField()),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=6)),
                ('hit_points', models.IntegerField()),
                ('mana_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=1, max_digits=6)),
                ('background', models.TextField()),
                ('size', models.CharField(choices=[('TN', 'Minúsculo'), ('SM', 'Pequeno'), ('MD', 'Médio'), ('LG', 'Grande'), ('HG', 'Enorme'), ('GG', 'Colossal')], max_length=2)),
                ('role', models.CharField(choices=[('TNK', 'Defensor'), ('HLR', 'Curador'), ('MDG', 'Dano Corpo a Corpo'), ('RDG', 'Dano Longo Alcance'), ('SPT', 'Suporte'), ('CST', 'Conjurador'), ('SPC', 'Especialista')], max_length=3)),
                ('picture', models.ImageField(upload_to='characters/pictures/%Y/%m/%d')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.classe')),
                ('faith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.faith')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.origin')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.race')),
            ],
        ),
    ]
