# Generated by Django 5.2.6 on 2025-10-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='attributes',
        ),
        migrations.AddField(
            model_name='character',
            name='att_char',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='att_con',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='att_dex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='att_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='att_sab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='att_str',
            field=models.IntegerField(default=0),
        ),
    ]
