# Generated by Django 5.2.6 on 2025-10-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_character_attributes_character_att_char_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='size',
        ),
    ]
