# Generated by Django 5.2.6 on 2025-10-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_race_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='size',
            field=models.CharField(choices=[('TN', 'Minúsculo'), ('SM', 'Pequeno'), ('MD', 'Médio'), ('LG', 'Grande'), ('HG', 'Enorme'), ('GG', 'Colossal')], default='MD', max_length=2),
        ),
    ]
